ip_forward: true
network_compression_threshold: 256
stats: 03e59ae4-1ee4-4059-acb0-1aa06f0deeb4
permissions:
  default:
  - skinsrestorer.playercmds
  - changeskin.command.setskin
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeealiases.lobby
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  SteveGrKek:
  - admin
  SteveGrKek123:
  - admin
  Odmen:
  - admin
servers:
  Auth:
    motd: '&5&l✤ &9&lｆｉｎｅ&6&lＷｏｒｌｄ &5&l✤'
    address: 127.0.0.1:21071
    restricted: false
  survival:
    motd: '&bｆｉｎｅ&eＷｏｒｌｄ'
    address: 127.0.0.1:23042
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '&bｆｉｎｅ&eＷｏｒｌｄ'
  priorities:
  - Auth
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1000
  tab_size: 80
  ping_passthrough: false
  force_default_server: true
  proxy_protocol: false
prevent_proxy_connections: false
player_limit: -1
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
